"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  const isActive = (path: string) => pathname === path;

  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <ul className="flex justify-center space-x-12 py-4">
            <li>
              <a
                href="/welcome"
                className={
                  isActive("/welcome") ? "btn-green-active" : "btn-green"
                }
              >
                Welcome
              </a>
            </li>
            <li>
              <a
                href="/task"
                className={isActive("/task") ? "btn-green-active" : "btn-green"}
              >
                Exercise
              </a>
            </li>
          </ul>
        </header>

        <main className="py-16">{children}</main>
      </body>
    </html>
  );
}
